world_size:
- 640.0
- 975.0
pixel_points:
- - 539.5
  - 586.3125
- - 1358.5
  - 595.3125
- - 1727.5
  - 1078.3125
- - 191.5
  - 1073.8125
world_points_cm:
- - 0.0
  - 0.0
- - 640.0
  - 0.0
- - 640.0
  - 975.0
- - 0.0
  - 975.0
homography:
- - -23.738357554645596
  - -16.94553523900855
  - 22742.223030552497
- - 1.2771643205005632
  - -116.22195316555215
  - 67453.35376446774
- - 0.0011237934175863844
  - -0.05567269187242028
  - 1.0
