world_size:
- 975.0
- 457.0
pixel_points:
- - 1391.5
  - -0.1875
- - 1754.5
  - 623.8125
- - 1727.5
  - 1078.3125
- - 1358.5
  - 595.3125
world_points_cm:
- - 0.0
  - 457.0
- - 975.0
  - 457.0
- - 975.0
  - 0.0
- - 0.0
  - 0.0
homography:
- - 1.0484425017140175
  - 0.058100088256192284
  - -1458.8968473685075
- - 0.5220898343291763
  - -0.39886366225148245
  - -471.8105160021006
- - -0.00031804494658699175
  - -2.318465307878636e-05
  - 1.0
