world_size:
- 975.0
- 457.0
pixel_points:
- - 520.0
  - -1.6875
- - 157.0
  - 631.3125
- - 191.5
  - 1073.8125
- - 539.5
  - 586.3125
world_points_cm:
- - 0.0
  - 457.0
- - 975.0
  - 457.0
- - 975.0
  - 0.0
- - 0.0
  - 0.0
homography:
- - -2.473149732499255
  - 0.08201772072063858
  - 1286.1762658033285
- - -1.2704251115408927
  - -0.906888079623037
  - 1217.1141648602934
- - 0.00042463519135371074
  - -0.00014675240469709346
  - 1.0
