world_size:
- 975.0
- 457.0
pixel_points:
- - 926.0
  - 1.0
- - 1168.0
  - 417.0
- - 1150.0
  - 720.0
- - 904.0
  - 398.0
world_points_cm:
- - 0.0
  - 457.0
- - 975.0
  - 457.0
- - 975.0
  - 0.0
- - 0.0
  - 0.0
homography:
- - 1.5738535785488512
  - 0.08721606732512541
  - -1457.4756298035613
- - 0.7837272456425874
  - -0.5987481441865731
  - -470.187668674643
- - -0.00047742834583675134
  - -3.480329519777053e-05
  - 1.0
