world_size:
- 640.0
- 975.0
pixel_points:
- - 358.0
  - 392.0
- - 904.0
  - 398.0
- - 1150.0
  - 720.0
- - 126.0
  - 717.0
world_points_cm:
- - 0.0
  - 0.0
- - 640.0
  - 0.0
- - 640.0
  - 975.0
- - 0.0
  - 975.0
homography:
- - -32.466135738642976
  - -23.175826127277457
  - 20707.80043632695
- - 1.7467336357423515
  - -158.95276085255585
  - 61684.15161260614
- - 0.001536970365286158
  - -0.07614162470399925
  - 1.0
