world_size:
- 640.0
- 457.0
pixel_points:
- - 345.0
  - 0.0
- - 926.0
  - 1.0
- - 904.0
  - 398.0
- - 358.0
  - 392.0
world_points_cm:
- - 0.0
  - 457.0
- - 640.0
  - 457.0
- - 640.0
  - 0.0
- - 0.0
  - 0.0
homography:
- - 1.1260400010750693
  - -0.037343163300958784
  - -388.48380037089885
- - 0.01292245710202133
  - -1.1759435962839424
  - 456.3436501007818
- - 2.4113771610562104e-05
  - -0.00015451272807720133
  - 1.0
