homography:
- - 8.102547871498626
  - 4.6083241019148415
  - -4725.608482354785
- - 3.392434153931416e-16
  - 35.75822915018184
  - -14160.258743472006
- - 5.129001999238227e-19
  - 0.01499446114891591
  - 1.0
pixel_points:
- - 358.0
  - 396.0
- - 906.0
  - 396.0
- - 1103.0
  - 716.0
- - 176.0
  - 716.0
world_size:
- 640.0
- 975.0
