world_size:
- 975.0
- 457.0
pixel_points:
- - 345.0
  - 0.0
- - 103.0
  - 422.0
- - 126.0
  - 717.0
- - 358.0
  - 392.0
world_points_cm:
- - 0.0
  - 457.0
- - 975.0
  - 457.0
- - 975.0
  - 0.0
- - 0.0
  - 0.0
homography:
- - -3.7048740566279044
  - 0.12286572126572148
  - 1278.181549536627
- - -1.903146006400518
  - -1.3585534568766773
  - 1213.8792253870429
- - 0.0006361199580050373
  - -0.00021984078431053255
  - 1.0
