world_size:
- 640.0
- 975.0
pixel_points:
- - 539.5
  - 598.3125
- - 1363.5
  - 598.3125
- - 1727.5
  - 1079.3125
- - 194.5
  - 1075.8125
world_points_cm:
- - 0.0
  - 0.0
- - 640.0
  - 0.0
- - 640.0
  - 975.0
- - 0.0
  - 975.0
homography:
- - -9.901938593187872
  - -7.154280240104329
  - 9622.591167182278
- - -6.317763485542772e-15
  - -48.1568183528293
  - 28812.826380727187
- - -6.061768309718285e-05
  - -0.022841063370439993
  - 1.0
