world_size:
- 640.0
- 457.0
pixel_points:
- - 518.0
  - -0.6875
- - 1391.5
  - -0.1875
- - 1363.5
  - 598.3125
- - 539.5
  - 598.3125
world_points_cm:
- - 0.0
  - 457.0
- - 640.0
  - 457.0
- - 640.0
  - 0.0
- - 0.0
  - 0.0
homography:
- - 0.731793943032088
  - -0.0262663936146742
  - -379.0873206362317
- - -5.0255244530058964e-17
  - -0.7626317260627264
  - 456.29209459990506
- - -9.010883162695074e-07
  - -9.457710548743863e-05
  - 1.0
