homography:
- - 1.1149750177351863
  - -0.04586015497111306
  - -381.0004349806362
- - 0.003861545276219352
  - 1.1159865848273816
  - -9.132554578258798
- - 8.449770845118903e-06
  - -0.00013373266022708417
  - 1.0
pixel_points:
- - 342.0
  - 7.0
- - 920.0
  - 5.0
- - 906.0
  - 396.0
- - 358.0
  - 396.0
world_size:
- 640.0
- 457.0
