world_size:
- 975.0
- 457.0
pixel_points:
- - 518.0
  - 1.3125
- - 171.0
  - 637.3125
- - 195.5
  - 1075.8125
- - 539.5
  - 598.3125
world_points_cm:
- - 0.0
  - 457.0
- - 975.0
  - 457.0
- - 975.0
  - 0.0
- - 0.0
  - 0.0
homography:
- - -2.8320955112082777
  - 0.10199338943212388
  - 1466.8916084822583
- - -1.4424969183318286
  - -1.0392019683898408
  - 1399.9946151522681
- - 0.0008215379417491757
  - -0.00010358557990363681
  - 1.0
